[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap_sol_move = "Fr85xkdi1fvpfR9XCb6uy3rJUDq2pmoH6UTKaTy4aUtQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/trieu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
